<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OS9T7E3" failures="1" tests="6" name="Test" time="7.384" errors="0" timestamp="2022-03-28T12:40:39 ICT">
  <testcase classname="DemoTestNG.chuViTest" name="tinhChuViTest" time="0.007"/>
  <testcase classname="DemoTestNG.chuViTest" name="tinhChuViTest2" time="0.0"/>
  <testcase classname="DemoTestNG.chuViTest" name="tinhChuViTest3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [5] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [10]
at DemoTestNG.chuViTest.tinhChuViTest3(chuViTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- tinhChuViTest3 -->
  <testcase classname="DemoTestNG.Lab4Test" name="getVatOnAmountTest" time="0.001"/>
  <testcase classname="DemoTestNG.Lab5_1Test" name="timKiemLMSFpoly" time="4.331"/>
  <testcase classname="DemoTestNG.ParametersTest" name="test" time="3.001"/>
</testsuite> <!-- Test -->
